---
title: "reclin introduction"
author: "Jan van der Laan"
output: html_document
---

```{r,echo=FALSE,results='hide',message=FALSE,warning=FALSE}
library(devtools)
load_all()
```

We will work with a pair of data sets with artificial data. They are tiny, but 
that allows us to see what happens. 
```{r}
data("linkexample1", "linkexample2")
print(linkexample1)
print(linkexample2)
```

We have two data sets with personal information. The second data set contains a
lot of errors, but we will try to link the second data set to the first. 


```{r}
pairs <- pairs_blocking(linkexample1, linkexample2, "postcode")
print(pairs)
```

```{r}
pairs <- pairs_compare(pairs, by = c("lastname", "firstname", "address", "sex"), 
  default_comparator = jaro_winkler(0.9))
```

```{r}
pairs <- score_simsum(pairs, var = "simsum")
pairs <- select_greedy(pairs, "weight", var = "greedy_weight", threshold = 0)
```

```{r}
m <- problink_em(p)


p <- score_problink(p, model = m, var = "weight")

p <- select_n_to_m(p, "weight", var = "ntom_weight", threshold = 0)


p <- select_n_to_m(p, "simsum", var = "ntom_simsum", threshold = 2)
p <- select_greedy(p, "simsum", var = "greedy_simsum", threshold = 2)

p <- add_from_x(p, id_x = "id") 
p <- add_from_y(p, id_y = "id")
p$true <- p$id_x == p$id_y

table(p$ntom_weight, p$true)
table(p$ntom_simsum, p$true)
table(p$greedy_simsum, p$true)
table(p$greedy_weight, p$true)

```

