# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

equivalence_rcpp <- function(a, b, n) {
    .Call('_reclin_equivalence_rcpp', PACKAGE = 'reclin', a, b, n)
}

greedy_rcpp <- function(x, y) {
    .Call('_reclin_greedy_rcpp', PACKAGE = 'reclin', x, y)
}

